// Alert actions
export const ALERT_PUSH = 'ALERT_PUSH';
export const ALERT_POP = 'ALERT_POP';

// User actions
export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING';
export const USER_LOGIN_REJECTED = 'USER_LOGIN_REJECTED';
export const USER_LOGIN_FULFILLED = 'USER_LOGIN_FULFILLED';
export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING';
export const USER_REGISTER_FULFILLED = 'USER_REGISTER_FULFILLED';
export const USER_REGESTER_REJECTED = 'USER_REGESTER_REJECTED';
export const USER_RESUME = 'USER_RESUME';
export const USER_LOGOUT = 'USER_LOGOUT';

// Schedule actions
export const SCHEDULE_GET_PENDING = 'SCHEDULE_GET_PENDING';
export const SCHEDULE_GET_FULFILLED = 'SCHEDULE_GET_FULFILLED';
export const SCHEDULE_GET_REJECTED = 'SCHEDULE_GET_REJECTED';

// Customer actions
export const CUSTOMER_LIST_PENDING = 'CUSTOMER_LIST_PENDING';
export const CUSTOMER_LIST_FULFILLED = 'CUSTOMER_LIST_FULFILLED';
export const CUSTOMER_LIST_REJECTED = 'CUSTOMER_LIST_REJECTED';
export const CUSTOMER_ADD_PENDING = 'CUSTOMER_ADD_PENDING';
export const CUSTOMER_ADD_FULFILLED = 'CUSTOMER_ADD_FULFILLED';
export const CUSTOMER_ADD_REJECTED = 'CUSTOMER_ADD_REJECTED';
