// Alert actions
export const ALERT_PUSH = 'ALERT_PUSH';
export const ALERT_POP = 'ALERT_POP';

// User actions
export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING';
export const USER_LOGIN_REJECTED = 'USER_LOGIN_REJECTED';
export const USER_LOGIN_FULFILLED = 'USER_LOGIN_FULFILLED';
export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING';
export const USER_REGISTER_FULFILLED = 'USER_REGISTER_FULFILLED';
export const USER_REGESTER_REJECTED = 'USER_REGESTER_REJECTED';
export const USER_RESUME = 'USER_RESUME';
